=== intel-secl/common-java/util/mtwilson-util-json-validation/src/test/resources/sample/flavor-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Root schema.",
  "description": "An explanation about the purpose of this instance.",
  "properties": {
    "label": {
      "type": "string",
      "title": "Label schema.",
      "description": "An explanation about the purpose of this instance."
    },
    "id": {
      "type": "string",
      "title": "Id schema.",
      "description": "An explanation about the purpose of this instance."
    },
    "description": {
      "type": "string",
      "title": "Description schema.",
      "description": "An explanation about the purpose of this instance."
    },
    "notBefore": {
      "type": "string",
      "title": "NotBefore schema.",
      "description": "An explanation about the purpose of this instance."
    },
    "notAfter": {
      "type": "null",
      "title": "NotAfter schema.",
      "description": "An explanation about the purpose of this instance."
    },
    "hardware": {
      "type": "object",
      "title": "Hardware schema.",
      "description": "An explanation about the purpose of this instance.",
      "properties": {
        "vendor": {
          "type": "string",
          "title": "Vendor schema.",
          "description": "An explanation about the purpose of this instance."
        },
        "features": {
          "type": "object",
          "title": "Features schema.",
          "description": "An explanation about the purpose of this instance.",
          "properties": {
            "AES-NI": {
              "type": "object",
              "title": "AES-NI schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "enabled": {
                  "type": "boolean",
                  "title": "Enabled schema.",
                  "description": "An explanation about the purpose of this instance."
                }
              }
            },
            "$anyOf": {
              "type": "array",
              "title": "$anyOf schema.",
              "description": "An explanation about the purpose of this instance.",
              "items": {
                "type": "object",
                "title": "1 schema.",
                "description": "An explanation about the purpose of this instance.",
                "properties": {
                  "SGX": {
                    "type": "object",
                    "title": "SGX schema.",
                    "description": "An explanation about the purpose of this instance.",
                    "properties": {
                      "enabled": {
                        "type": "boolean",
                        "title": "Enabled schema.",
                        "description": "An explanation about the purpose of this instance."
                      }
                    }
                  }
                }
              }
            },
            "TPM": {
              "type": "object",
              "title": "TPM schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "version": {
                  "type": "string",
                  "title": "Version schema.",
                  "description": "An explanation about the purpose of this instance."
                },
                "enabled": {
                  "type": "boolean",
                  "title": "Enabled schema.",
                  "description": "An explanation about the purpose of this instance."
                },
                "pcrs": {
                  "type": "object",
                  "title": "Pcrs schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "properties": {
                    "0": {
                      "type": "object",
                      "title": "0 schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "properties": {
                        "value": {
                          "type": "string",
                          "title": "Value schema.",
                          "description": "An explanation about the purpose of this instance."
                        }
                      }
                    },
                    "17": {
                      "type": "object",
                      "title": "17 schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "properties": {
                        "$oneOf": {
                          "type": "array",
                          "title": "$oneOf schema.",
                          "description": "An explanation about the purpose of this instance.",
                          "items": {
                            "type": "object",
                            "title": "1 schema.",
                            "description": "An explanation about the purpose of this instance.",
                            "properties": {
                              "value": {
                                "type": "string",
                                "title": "Value schema.",
                                "description": "An explanation about the purpose of this instance."
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "software": {
      "type": "object",
      "title": "Software schema.",
      "description": "An explanation about the purpose of this instance.",
      "properties": {
        "digestAlg": {
          "type": "string",
          "title": "DigestAlg schema.",
          "description": "An explanation about the purpose of this instance."
        },
        "measurements": {
          "type": "object",
          "title": "Measurements schema.",
          "description": "An explanation about the purpose of this instance.",
          "properties": {
            "/etc/hosts": {
              "type": "object",
              "title": "/etc/hosts schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "type": {
                  "type": "string",
                  "title": "Type schema.",
                  "description": "An explanation about the purpose of this instance."
                },
                "digest": {
                  "type": "string",
                  "title": "Digest schema.",
                  "description": "An explanation about the purpose of this instance."
                }
              }
            },
            "$oneOf": {
              "type": "array",
              "title": "$oneOf schema.",
              "description": "An explanation about the purpose of this instance.",
              "items": {
                "type": "object",
                "title": "1 schema.",
                "description": "An explanation about the purpose of this instance.",
                "properties": {
                  "/opt/mtwilson/java/mtwilson-util-crypto-3.0.jar": {
                    "type": "object",
                    "title": "/opt/mtwilson/java/mtwilson-util-crypto-3.0.jar schema.",
                    "description": "An explanation about the purpose of this instance.",
                    "properties": {
                      "type": {
                        "type": "string",
                        "title": "Type schema.",
                        "description": "An explanation about the purpose of this instance."
                      },
                      "digest": {
                        "type": "string",
                        "title": "Digest schema.",
                        "description": "An explanation about the purpose of this instance."
                      }
                    }
                  }
                }
              }
            },
            "/etc/apache2/mods.enabled": {
              "type": "object",
              "title": "/etc/apache2/mods.enabled schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "type": {
                  "type": "string",
                  "title": "Type schema.",
                  "description": "An explanation about the purpose of this instance."
                },
                "digest": {
                  "type": "string",
                  "title": "Digest schema.",
                  "description": "An explanation about the purpose of this instance."
                },
                "include": {
                  "type": "string",
                  "title": "Include schema.",
                  "description": "An explanation about the purpose of this instance."
                }
              }
            }
          }
        }
      }
    },
    "boot": {
      "type": "object",
      "title": "Boot schema.",
      "description": "An explanation about the purpose of this instance.",
      "properties": {
        "bios": {
          "type": "object",
          "title": "Bios schema.",
          "description": "An explanation about the purpose of this instance.",
          "properties": {
            "vendor": {
              "type": "string",
              "title": "Vendor schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "version": {
              "type": "string",
              "title": "Version schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "digestAlg": {
              "type": "string",
              "title": "DigestAlg schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "digest": {
              "type": "string",
              "title": "Digest schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "pcr": {
              "type": "integer",
              "title": "Pcr schema.",
              "description": "An explanation about the purpose of this instance."
            }
          }
        },
        "initrd": {
          "type": "object",
          "title": "Initrd schema.",
          "description": "An explanation about the purpose of this instance.",
          "properties": {
            "digestAlg": {
              "type": "string",
              "title": "DigestAlg schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "digest": {
              "type": "string",
              "title": "Digest schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "pcr": {
              "type": "integer",
              "title": "Pcr schema.",
              "description": "An explanation about the purpose of this instance."
            }
          }
        }
      }
    },
    "external": {
      "type": "object",
      "title": "External schema.",
      "description": "An explanation about the purpose of this instance.",
      "properties": {
        "geotag": {
          "type": "object",
          "title": "Geotag schema.",
          "description": "An explanation about the purpose of this instance.",
          "properties": {
            "digestAlg": {
              "type": "string",
              "title": "DigestAlg schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "digest": {
              "type": "string",
              "title": "Digest schema.",
              "description": "An explanation about the purpose of this instance."
            },
            "certificate": {
              "type": "object",
              "title": "Certificate schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "attributes": {
                  "type": "object",
                  "title": "Attributes schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "properties": {
                    "2.5.4.789.1": {
                      "type": "object",
                      "title": "2.5.4.789.1 schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "properties": {
                        "country": {
                          "type": "string",
                          "title": "Country schema.",
                          "description": "An explanation about the purpose of this instance."
                        },
                        "$oneOf": {
                          "type": "array",
                          "title": "$oneOf schema.",
                          "description": "An explanation about the purpose of this instance.",
                          "items": {
                            "type": "object",
                            "title": "1 schema.",
                            "description": "An explanation about the purpose of this instance.",
                            "properties": {
                              "state": {
                                "type": "string",
                                "title": "State schema.",
                                "description": "An explanation about the purpose of this instance."
                              },
                              "city": {
                                "type": "string",
                                "title": "City schema.",
                                "description": "An explanation about the purpose of this instance."
                              }
                            }
                          }
                        }
                      }
                    },
                    "2.5.4.789.2": {
                      "type": "object",
                      "title": "2.5.4.789.2 schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "properties": {
                        "country": {
                          "type": "array",
                          "title": "Country schema.",
                          "description": "An explanation about the purpose of this instance.",
                          "items": {
                            "type": "string",
                            "title": "0 schema.",
                            "description": "An explanation about the purpose of this instance."
                          }
                        },
                        "$oneOf": {
                          "type": "array",
                          "title": "$oneOf schema.",
                          "description": "An explanation about the purpose of this instance.",
                          "items": {
                            "type": "object",
                            "title": "1 schema.",
                            "description": "An explanation about the purpose of this instance.",
                            "properties": {
                              "state": {
                                "type": "array",
                                "title": "State schema.",
                                "description": "An explanation about the purpose of this instance.",
                                "items": {
                                  "type": "string",
                                  "title": "0 schema.",
                                  "description": "An explanation about the purpose of this instance."
                                }
                              },
                              "city": {
                                "type": "array",
                                "title": "City schema.",
                                "description": "An explanation about the purpose of this instance.",
                                "items": {
                                  "type": "string",
                                  "title": "0 schema.",
                                  "description": "An explanation about the purpose of this instance."
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "issuer": {
                  "type": "object",
                  "title": "Issuer schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "properties": {
                    "$anyOf": {
                      "type": "array",
                      "title": "$anyOf schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "items": {
                        "type": "object",
                        "title": "1 schema.",
                        "description": "An explanation about the purpose of this instance.",
                        "properties": {
                          "publicKey": {
                            "type": "string",
                            "title": "PublicKey schema.",
                            "description": "An explanation about the purpose of this instance."
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== intel-secl/common-java/util/mtwilson-util-json-validation/src/test/resources/sample/flavor-bad10.json
{
  "label": "Key Escrow on ClearLinux 8830",
  "id": "author@site.edu/e4746425-f56b-4b99-83d9-93262f1581fa",
  "description": "Measurements of binaries and settings",
  "notBefore": "2016-07-18T09:23:34+00:00",
  "notAfter": "",
  "hardware": {
    "features": {
      "AES-NI": { "enabled": true },
        "TXT": { "enabled": true } ,
         "SGX": { "enabled": true } ,
      
      "TPM": {
        "version": "1.2",
        "enabled": true,
        "pcrs": {
          "0": { "value": "2aae6c35c94fcfb415dbe95f408b9ce91ee846ed" },
          "17": 
            { "value": "f1f0188d7e74ce2e9b395726ee39848bcd92e869" }
            
          
        }
      }
    }
  },
  "software": {
    "digestAlg": "sha-256",
    "measurements": {
      "/etc/hosts": { "type": "file", "digest": "2cab4cce4d11a47acdd4625b63f207974824d1d7f1804f4d4825f7a4472d39f9" },
      
        
          "/opt/mtwilson/java/mtwilson-util-crypto-3.1.jar": {
            "type": "file",
            "digest": "98f2b01890b947c4789d2907ca3111c50fedfcb1dba028d06e16bb04852e975a" 
          }
        ,
        
      "/opt/mtwilson/java/mtwilson-util-crypto-3.2.jar": {
            "type": "file",
            "digest": "98f2b01890b947c4789d2907ca3111c50fedfcb1dba028d06e16bb04852e975a" 
          }
        ,
      "/etc/apache2/mods.enabled": {
        "type": "dir",
        "digest": "3890b04101b1b2178aaddbc2a2d692611d5e6668835c01d4e2710c2785427738",
        "include": "[0-9A-Za-z_-]*(?:.load|.conf)" 
      }
    }
  },
  "boot": {
    "bios": {
      "vendor": "Intel",
      "version": "1.2.3",
      "digestAlg": "sha-1",
      "digest": "ac9ff4e0e2a43c3124ee555035d31b42b89a7d6e",
      "pcr": 0
    },
    "initrd": {
      "digestAlg": "sha-1",
      "digest": "99b3b7a100fded7c7eb1c59f4d75d84137822596",
      "pcr": 8
    }
  },
  "external": {
    "geotag": {
      "digestAlg": "sha-1",
      "digest": "f21edca8819e2f854e84dae73570c061cafacf65",
      "certificate": {
        "attributes": {
          "2.5.4.789.1": {
              "country": "US",
              
                
                 "state": "OR", "city": "Hillsboro" 
              
          },
          "2.5.4.789.2": {
              "country": ["US"],
              
                
                "state": ["OR"], "city": ["Hillsboro"] 
              
          }
        },
        "issuer": {
         
             "publicKey": [ "...base64 of DER-encoded..." ]
           
          
        }
      }
    }
  }
}
